title: Ubipanas.com — Info & Hiburan Malaysia
description: Ubipanas — Portal info dan Hiburan Malaysia
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ubipanas.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ubipanas # add your name
author-img: # add your photo
about-author: # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
kramdown:
  parse_block_html: true
  
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

include: ["_pages"]

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

header_pages:
  - network.md